### ISSUE TITLE
Node.js v18 Compatibility Test for [dashboards-search-relevance]

### ISSUE THREAD

**Issue by ananzh** [opensearch-project/dashboards-search-relevance#202]
## Introduction
As part of our continued efforts to improve OpenSearch Dashboards, we are planning to upgrade the underlying Node.js version from v14 to v18. This change will enhance performance, add new features, and bolster security. However, such major version changes might also affect the compatibility of existing plugins. Here is more introduction: https://github.com/opensearch-project/OpenSearch-Dashboards/issues/3601.

Therefore, we kindly request assistance in testing this plugin the compatibility of with this new version of Node.js. We've prepared a branch with the Node.js v18 upgrade, which you can find here:
https://github.com/AMoo-Miki/OpenSearch-Dashboards/tree/node-18-webpack-4

## Steps to Proceed
* If you think your plugin won't be affected by OpenSearch Dashboards Node.js upgrade. Pls ignore the rest steps and close the issue directly.
* Pull the provided branch that includes the Node.js v18 upgrade and OpenSearch 3.0.0.
* Hook up your plugin with the updated OpenSearch Dashboards.
* Run your existing test suites and perform manual testing as necessary.
* If no issues are encountered, feel free to close this issue.
* If there are any problems, report them in this issue thread and also **link them in the overall OpenSearch Dashboards Node.js upgrade issue thread** https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4058
The purpose of linking any questions or issues back to the main issue is to maintain visibility and transparency among all plugin owners. A problem encountered by one plugin might also affect others. This shared knowledge base will foster collaborative problem-solving and prevent duplication of effort.

We appreciate your support and cooperation in ensuring a smooth transition to Node.js v18 for the entire OpenSearch Dashboards community.

**Comment by ananzh** [comment]
The official Node.js 18 PR raised in OSD: https://github.com/opensearch-project/OpenSearch-Dashboards/pull/4071

**Comment by ananzh** [comment]
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/4071 support node 14, 16 and 18. Pls test on node 18. 
```
nvm install 18.16.0
nvm use 18.16.0
```

**Comment by noCharger** [comment]
https://github.com/opensearch-project/dashboards-search-relevance/issues/204

**Comment by sejli** [comment]
Cypress tests pass, sanity tests on local OSD instance pass. `dashboards-search-relevance` is compatible with Node 18, closing issue. Thanks!

**Comment by noCharger** [comment]
$ scripts/use_node ./preinstall_check
[1/5] Validating package.json...
[2/5] Resolving packages...
warning Resolution field "typescript@4.0.2" is incompatible with requested version "typescript@~4.5.2"
[3/5] Fetching packages...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
error An unexpected error occurred: "https://registry.yarnpkg.com/rxjs/-/rxjs-6.6.7.tgz: ESOCKETTIMEDOUT".
info If you think this is a bug, please open a bug report with the information provided in "D:\\a\\dashboards-search-relevance\\dashboards-search-relevance\\OpenSearch-Dashboards\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
ERROR [bootstrap] failed:
ERROR Error: Command failed with exit code 1: C:\npm\prefix\node_modules\yarn\bin\yarn.js install --non-interactive
          at makeError (D:\a\dashboards-search-relevance\dashboards-search-relevance\OpenSearch-Dashboards\packages\osd-pm\dist\index.js:25045:11)
          at handlePromise (D:\a\dashboards-search-relevance\dashboards-search-relevance\OpenSearch-Dashboards\packages\osd-pm\dist\index.js:23981:26)
          at processTicksAndRejections (internal/process/task_queues.js:95:5)
          at async installInDir (D:\a\dashboards-search-relevance\dashboards-search-relevance\OpenSearch-Dashboards\packages\osd-pm\dist\index.js:23704:3)
          at async Project.installDependencies (D:\a\dashboards-search-relevance\dashboards-search-relevance\OpenSearch-Dashboards\packages\osd-pm\dist\index.js:15[16](https://github.com/opensearch-project/dashboards-search-relevance/actions/runs/5085431385/jobs/9138888584?pr=205#step:10:17)8:5)
          at async Object.run (D:\a\dashboards-search-relevance\dashboards-search-relevance\OpenSearch-Dashboards\packages\osd-pm\dist\index.js:9[18](https://github.com/opensearch-project/dashboards-search-relevance/actions/runs/5085431385/jobs/9138888584?pr=205#step:10:19)8:11)
          at async runCommand (D:\a\dashboards-search-relevance\dashboards-search-relevance\OpenSearch-Dashboards\packages\osd-pm\dist\index.js:56360:5)
          at async Object.run (D:\a\dashboards-search-relevance\dashboards-search-relevance\OpenSearch-Dashboards\packages\osd-pm\dist\index.js:278:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Process completed with exit code 1.

**Comment by sejli** [comment]
`osd bootstrap` error in workflow is unrelated to Node 18, there are no compatibility issues, closing again
